<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
    public function render($request, Throwable $e)
    {
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        $guard = $exception->guards()[0];
        if ($guard == config("auth.guard_names.admin")){
            return redirect(config('auth.guard_failed_redirect.admin'));
        }
        return parent::unauthenticated($request, $exception); // TODO: Change the autogenerated stub
    }
}
